name: Deploy to ECS Fargate

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: wisecow
  ECR_REGISTRY: 486991249421.dkr.ecr.eu-north-1.amazonaws.com
  IMAGE_TAG: ${{ github.run_number }}
  S3_BUCKET: wisecow-trivy-reports

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Trivy Scan ECR Image
        run: |
          ./trivy image --timeout 5m --skip-update -f json -o trivy-report.json $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "Trivy scan completed with vulnerabilities or warnings."

      - name: Upload Trivy Report to S3
        if: success()
        run: |
          if [ -f trivy-report.json ]; then
            aws s3 cp trivy-report.json s3://$S3_BUCKET/trivy-report-${IMAGE_TAG}.json
          else
            echo "❌ trivy-report.json not found. Skipping upload."
          fi


      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster wisecow-cluster \
            --service wisecow-service \
            --force-new-deployment \
            --region $AWS_REGION
